/* 
 * Here is where system computed values get stored.
 * These values should only change when the target compile platform changes.
 */

#cmakedefine VTKBXH_BUILD_SHARED_LIBS
#ifndef VTKBXH_BUILD_SHARED_LIBS
#define VTKBXH_STATIC
#endif

#if defined(WIN32) && !defined(VTKBXH_STATIC)
#pragma warning ( disable : 4275 )

#if defined(vtkBXH_EXPORTS)
#define VTK_BXH_EXPORT __declspec( dllexport ) 
#else
#define VTK_BXH_EXPORT __declspec( dllimport ) 
#endif
#else
#define VTK_BXH_EXPORT
#endif
