/* 
 * Here is where system computed values get stored.
 * These values should only change when the target compile platform changes.
 */

#cmakedefine VTKAG_BUILD_SHARED_LIBS
#ifndef VTKAG_BUILD_SHARED_LIBS
#define VTKAG_STATIC
#endif

#if defined(WIN32) && !defined(VTKAG_STATIC)
#pragma warning ( disable : 4275 )

#if defined(vtkAG_EXPORTS)
#define VTK_AG_EXPORT __declspec( dllexport ) 
#else
#define VTK_AG_EXPORT __declspec( dllimport ) 
#endif
#else
#define VTK_AG_EXPORT
#endif
