/* 
 * Here is where system computed values get stored.
 * These values should only change when the target compile platform changes.
 */

#cmakedefine VTKITK_BUILD_SHARED_LIBS
#ifndef VTKITK_BUILD_SHARED_LIBS
#define VTKITK_STATIC
#endif

#if defined(WIN32) && !defined(VTKITK_STATIC)
#pragma warning ( disable : 4275 )

#if defined(vtkITK_EXPORTS)
#define VTK_ITK_EXPORT __declspec( dllexport ) 
#else
#define VTK_ITK_EXPORT __declspec( dllimport ) 
#endif
#else
#define VTK_ITK_EXPORT
#endif
